name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: "https://brdgm.me/${{ vars.APP_NAME }}"

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - run: npm install
    - run: npm run test:unit
    - run: npm run build

    - name: Copy to Site
      uses: cpina/github-action-push-to-another-repository@v1.7.2
      env:
        API_TOKEN_GITHUB: ${{ secrets.GH_SITE_DEPLOY_PAT }}
      with:
        source-directory: dist
        destination-repository-username: brdgm
        destination-repository-name: brdgm.github.io
        destination-github-username: ${{ secrets.GH_SITE_DEPLOY_USERNAME }}
        user-email: ${{ secrets.GH_SITE_DEPLOY_EMAIL }}
        user-name: ${{ secrets.GH_SITE_DEPLOY_NAME }}
        target-branch: main
        commit-message: deploy ${{ vars.APP_NAME }}
        target-directory: ${{ vars.APP_NAME }}
